version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: events_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: events_queue
    ports:
      - "6379:6379"
